In [1]:
import pandas as pd
import random
from faker import Faker

fake = Faker("en_IN")

random.seed(42)
Faker.seed(42)

TOTAL_CUSTOMERS = 100000

In [2]:
cities = [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Surat",
    "Indore",
    "Nagpur",
    "Patna",
    "Bhopal",
    "Kochi",
    "Coimbatore",
    "Visakhapatnam",
    "Chandigarh",
    "Kanpur"
]

In [3]:
occupations = {

    "Student":22,

    "Software Engineer":12,

    "Business":10,

    "Teacher":6,

    "Doctor":5,

    "Government Employee":6,

    "Private Employee":18,

    "Freelancer":5,

    "Retired":4,

    "Self Employed":7,

    "Other":5

}

In [4]:
membership = {

    "Regular":72,

    "Gold":22,

    "Platinum":6

}

In [5]:
genres = [

"Action",

"Drama",

"Comedy",

"Crime",

"Thriller",

"Romance",

"Sci-Fi",

"Horror",

"Animation"

]

In [6]:
languages = [

"Hindi",

"English",

"Tamil",

"Telugu",

"Kannada",

"Malayalam"

]

In [7]:
customers = []

for customer_id in range(1, TOTAL_CUSTOMERS + 1):

    age = random.randint(18, 65)

    customers.append({

        "customer_id": customer_id,

        "customer_name": fake.name(),

        "gender": random.choice(["Male", "Female"]),

        "age": age,

        "city": random.choice(cities),

        "occupation": random.choices(
            population=list(occupations.keys()),
            weights=list(occupations.values()),
            k=1
        )[0],

        "membership": random.choices(
            population=list(membership.keys()),
            weights=list(membership.values()),
            k=1
        )[0],

        "preferred_genre": random.choice(genres),

        "preferred_language": random.choice(languages),

        "monthly_movie_budget": random.randint(300,3000),

        "food_purchase_probability": round(random.uniform(0.20,0.90),2),

        "app_rating": round(random.uniform(3.0,5.0),1)

    })

In [8]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,customer_id,customer_name,gender,age,city,occupation,membership,preferred_genre,preferred_language,monthly_movie_budget,food_purchase_probability,app_rating
0,1,Aryan Maharaj,Male,58,Mumbai,Private Employee,Regular,Comedy,Malayalam,719,0.67,4.8
1,2,Udant Dewan,Female,23,Delhi,Student,Regular,Animation,Kannada,408,0.59,4.4
2,3,Gagan Sami,Female,62,Ahmedabad,Teacher,Regular,Action,English,2031,0.44,3.3
3,4,Ayushman Chander,Male,39,Bengaluru,Business,Regular,Romance,Kannada,1383,0.76,4.5
4,5,Viraj Tiwari,Male,52,Nagpur,Student,Regular,Romance,Kannada,1087,0.69,3.1

In [9]:
customers_df.to_csv(

"../Dataset/customers.csv",

index=False

)

print("Customers Dataset Created Successfully!")

Customers Dataset Created Successfully!

In [11]:
customers_df.describe(include = "all")

,customer_id,customer_name,gender,age,city,occupation,membership,preferred_genre,preferred_language,monthly_movie_budget,food_purchase_probability,app_rating
count,100000.000000,100000,100000,100000.000000,100000,100000,100000,100000,100000,100000.000000,100000.000000,100000.000000
unique,NaN,84095,2,NaN,20,11,3,9,6,NaN,NaN,NaN
top,NaN,Dalbir Kala,Male,NaN,Lucknow,Student,Regular,Drama,Hindi,NaN,NaN,NaN
freq,NaN,6,50198,NaN,5132,22038,72085,11284,16927,NaN,NaN,NaN
mean,50000.500000,NaN,NaN,41.500890,NaN,NaN,NaN,NaN,NaN,1651.494860,0.550198,3.999734
std,28867.657797,NaN,NaN,13.835586,NaN,NaN,NaN,NaN,NaN,781.706385,0.201375,0.579144
min,1.000000,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,300.000000,0.200000,3.000000
25%,25000.750000,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,NaN,973.000000,0.380000,3.500000
50%,50000.500000,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,NaN,1655.000000,0.550000,4.000000
75%,75000.250000,NaN,NaN,53.000000,NaN,NaN,NaN,NaN,NaN,2330.000000,0.720000,4.500000
max,100000.000000,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,NaN,3000.000000,0.900000,5.000000

In [12]:
customers_df["membership"].value_counts()

membership
Regular     72085
Gold        21944
Platinum     5971
Name: count, dtype: int64